/**
 * React component rendering a kumihimo diagram.
 */

import { useEffect } from 'react';
import type { ReactNode } from 'react';

import type { CompileOptions, Diagnostic } from '@love-rox/kumihimo-core';

import { useKumihimo } from './useKumihimo.js';

/** Props accepted by {@link Kumihimo}. */
export interface KumihimoProps extends CompileOptions {
  /** The `.khm` source to draw. */
  source: string;
  /** Class applied to the wrapper element. */
  className?: string;
  /** Shown until the first compile finishes. */
  fallback?: ReactNode;
  /**
   * Called whenever a compile produces diagnostics.
   *
   * A drawing of faulty wiring still renders, so this is the only way a host application
   * learns that what it just drew has problems.
   */
  onDiagnostics?: (diagnostics: readonly Diagnostic[]) => void;
}

/**
 * Draw a kumihimo diagram.
 *
 * The SVG is generated by this package rather than fetched, and is inlined with
 * `dangerouslySetInnerHTML` because it is markup this library produced from the caller's
 * source — every text value in it is escaped by the renderer before it gets here.
 *
 * @param props - Source, presentation options and a diagnostics callback.
 * @returns The rendered diagram.
 */
export function Kumihimo({
  source,
  className,
  fallback,
  onDiagnostics,
  ...options
}: KumihimoProps): ReactNode {
  const { svg, diagnostics, pending, error } = useKumihimo(source, options);

  // In an effect, not in the render body: calling out during render fires on every
  // re-render even when nothing recompiled, and double-fires under StrictMode.
  useEffect(() => {
    if (diagnostics.length > 0) onDiagnostics?.(diagnostics);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [diagnostics]);

  if (error) {
    return (
      <div className={className} role="alert">
        {error.message}
      </div>
    );
  }

  // Only show the fallback before anything has ever been drawn. Once a diagram exists,
  // keeping it on screen through a recompile is what makes live editing bearable.
  if (pending && !svg) return <div className={className}>{fallback ?? null}</div>;

  return <div className={className} dangerouslySetInnerHTML={{ __html: svg }} />;
}
