/**
 * Vue component rendering a kumihimo diagram.
 */

import type { PropType, VNode } from 'vue';
import { computed, defineComponent, h, watch } from 'vue';

import type { CompileOptions, Diagnostic } from '@love-rox/kumihimo-core';

import { useKumihimo } from './useKumihimo.js';

/**
 * Draw a kumihimo diagram.
 *
 * The SVG is generated by this package from the caller's source, and every text value in
 * it is escaped by the renderer, so it is inlined with `v-html` rather than parsed again.
 *
 * @example
 * ```vue
 * <Kumihimo :source="src" theme="dark" @diagnostics="onDiagnostics" />
 * ```
 */
export const Kumihimo = defineComponent({
  name: 'Kumihimo',
  props: {
    /** The `.khm` source to draw. */
    source: { type: String, required: true },
    /** Colour theme name. */
    theme: { type: String, default: undefined },
    /** Any other compile option. */
    options: { type: Object as PropType<CompileOptions>, default: () => ({}) },
    /** Class applied to the wrapper element. */
    className: { type: String, default: undefined },
  },
  emits: {
    /** Fired whenever a compile produces diagnostics. */
    diagnostics: (value: readonly Diagnostic[]) => Array.isArray(value),
  },
  setup(props, { emit, slots }) {
    const config = computed<CompileOptions>(() =>
      props.theme === undefined ? props.options : { ...props.options, theme: props.theme },
    );
    const { svg, diagnostics, pending, error } = useKumihimo(() => props.source, config);

    watch(diagnostics, (value) => {
      if (value.length > 0) emit('diagnostics', value);
    });

    return (): VNode => {
      if (error.value) {
        return h('div', { class: props.className, role: 'alert' }, error.value.message);
      }
      // Only fall back before anything has ever been drawn. Keeping the previous diagram
      // on screen through a recompile is what makes live editing bearable.
      if (pending.value && !svg.value) {
        return h('div', { class: props.className }, slots['fallback']?.());
      }
      return h('div', { class: props.className, innerHTML: svg.value });
    };
  },
});

export default Kumihimo;
